# Generated by Django 4.1.3 on 2023-03-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_healthcaredetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCareDetails',
        ),
    ]
